[[section-introduction-and-goals]]
== Introduction and Goals

DeDe is an e-Commerce application (online retail system) in which users will be able to select and order products.

It follows SOLID principles, guaranteeing the client's privacy.

[role="arc42help"]

=== Requirements Overview

[role="arc42help"]
****

Requirements document:

English: https://arquisoft.github.io/course2122/labAssignmentDescription.html

Spanish: https://arquisoft.github.io/course2122/labEnunciadoPractica.html


* The system will emulate an online shopping system where end-users can select and order products to buy.

* Once a user selects the products to buy, the system will calculate the delivery costs by looking up the desired address of the end-users in their pods and calculating the costs according to the distance from the distribution center to that address.

* The system will show the final costs of the products to buy and once the user decides to buy them, it will record the event simulating that the sale has been done and it can proceed with the delivery.

* The system will allow the users to visualize the orders done.

* The application should be accessible and deployed using a continuous integration system.

* Allow a user to have more than one shipping address in their pods (e.g. Home, work, Gym, School etc.).

* Add the possibility to include estimation of time people are at a location (e.g. Monday-Thursday work 09.00-18.00) and restrict some of the addresses to be used for delivery at some point in time.

* Add pick-up locations that the delivery services can use. Based on the delivery address the pick-up location could be calculated (this can either be by one of the addresses in the profile or a pick-up location that's on the route of the receiver (e.g. between home and work).

* In order to calculate the delivery costs, external APIs from different carriers could be used and selected, so the users can compare and select the carrier.

* The system can allow some users with administrative roles to visualize statistics about products ordered and monitor the state of orders.

* Implement both a web application and a mobile application.

* Implement an emulator of the delivery system which can notify the users when the products have arrived and keep track of the deliveries.

* Support for different types of actors like customers, managers, administrators, etc. who can do different actions like inventory management, prices changes, items cataloging, etc.

* Add the possibility that there are several distribution centers or warehouses where the products are stored.

* Add the possibility that the users can add or update their address information to their pods directly from the app.

* Add ratings and reviews to products or distribution centers so the users can provide feedback about their experience.

[role="arc42help"]
****
=== Quality Goals

[options="header",cols="1,2,2"]
|===
|Quality Goal|Motivation|Priority
| Privacy | The treatment of private information will be decentralized, ensuring customer privacy | High
| Usability | All users must be able to use it, whether they have previous knowledge about the application or not | High
| Integrity| Data must be consistent and complete at all times | High
| Efficiency | Making a purchase should be easy for the user, reducing response and load times | High
| Testability | Major components should be easily tested and fixed | Medium
| Modifiability | The architecture must be easy to modify, adding new features or changing existing ones | Medium
|===


=== Stakeholders


[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Client | They interact directly with the application. They select the products to purchase and view their order history. | The aim is for the customer to be able to interact with the application intuitively and have a comfortable shopping experience. In addition, their privacy is respected in accordance with the SOLID principles.
| Administrator | They are in charge of modifying prices, calculating inventories, seeing all orders placed or placing orders with suppliers. | Administrators will be able to access their exclusive functions through a simple login. 
| Development Team | They are the creators of the application. They can modify, update and improve it. | Develop a complete application that contain the requirements. Learn to work in a team efficiently and learn new technologies.
|===
