[[section-runtime-view]]
== Runtime View


[role="arc42help"]

=== Add products to the shopping cart


[plantuml,"Add Products to the shopping cart",png]
----
actor Client
entity DeDe
database Database
Client -> DeDe: Selects a product cattegory
DeDe -> Database: Asks for the protucts of the selected cattegory
Database --> DeDe : Returns the searched products
DeDe --> Client : Shows the products
Client -> DeDe : Adds the products to the shopping cart
----
_The user, identified as a client, selects the cattegory of the product of its choice and the DeDe app returns the filtered products to them. Then, the user can scroll through de app looking for the returned products and press the button "Add to Cart" to add them into the shopping cart and pay for them whenever they want._

=== Paying process
[plantuml,"Paying Process",png]
----
actor Client
entity DeDe
database Database
database UserPod
Client -> DeDe: Presses the pay button
DeDe --> Client : Takes the client to the paying page
DeDe -> UserPod: Asks for the client's Address
UserPod --> DeDe: Returns the client Address
DeDe -> DeDe : Calculates the shipping price
DeDe --> Client : Returns the shipping price and the final price
Client -> DeDe : Presses the pay button
DeDe -> Database : Saves the order data
DeDe --> Client : Returns the order validation
----
_The user presses the pay button on their shopping cart and the DeDe app takes them to the paying page where they can see the total price to pay in addition to the shipping price previously calculated by the DeDe application after asking the user's pod for their address and calculating the distance from that address to the distribution center. After seeing the final price, the client must press the pay button so the DeDe app registers the order on the database and returns the confirmation_
=== ...

=== <Runtime Scenario n>
