[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
=== 6.2 Register User

[plantuml,"Sequence diagram",png]
----
@startuml
User-> WebApp : Register
WebApp-> ApiRest : send user data
ApiRest -> SOLID_POD : store user data
SOLID_POD -> ApiRest : return data location
ApiRest -> DataBase: store data location
ApiRest -> WebApp: Notify success
WebApp-> User: Notify success
@enduml
----

=== 6.3 Login User
----
@startuml
User-> WebApp : Login
WebApp-> ApiRest : send login data
ApiRest -> DataBase : find data location
ApiRest -> SOLID_POD : load login data
ApiRest -> ApiRest : check login data
ApiRest -> WebApp: Notify success
WebApp-> User: Notify success
@enduml
----

=== <Runtime Scenario n>
