[[section-runtime-view]]
== Runtime View


[role="arc42help"]

=== Add products to the shopping cart


[plantuml,"Add Products to the shopping cart",png]
----
actor User
entity Webapp
entity Restapi
database Database
User-> Webapp: Selects a product cattegory
Webapp -> Restapi : Sends petition 
Restapi-> Database: Asks for the protucts of the selected cattegory
Database --> Restapi: Returns the searched products
Restapi --> Webapp : Returns the searched products
Webapp --> User: Shows the products
User-> Webapp: Presses de add button
Webapp -> Restapi : Sends the added products
Restapi-> Database: Storages the information so the client can pay anytime
----
_The user, identified as a client, selects the cattegory of the product of its choice and the DeDe app returns the filtered products to them. Then, the user can scroll through de app looking for the returned products and press the button "Add to Cart" to add them into the shopping cart and pay for them whenever they want._

=== Paying process
[plantuml,"Paying Process",png]
----
actor User
entity Webapp
entity Restapi
database Database
database UserPod
User-> Webapp: Presses the pay button
Webapp -> Restapi: Sends the petition
Webapp--> User: Takes the client to the paying page
Restapi-> UserPod: Asks for the client's Address
UserPod --> Restapi: Returns the client Address
Restapi -> Restapi : Calculates the shipping price
Restapi --> Webapp : Returns the calculated data
Webapp --> User: Returns the shipping price and the final price
User-> Webapp: Presses the pay button
Webapp -> Restapi : Sends a petition to save the order data
Restapi -> Database : Sends a petition to save the order data
Database -> Database : saves the order data
Restapi --> Webapp: Returns the order validation
Webapp --> User: Shows the order validation
----
_The user presses the pay button on their shopping cart and the DeDe app takes them to the paying page where they can see the total price to pay in addition to the shipping price previously calculated by the DeDe application after asking the user's pod for their address and calculating the distance from that address to the distribution center. After seeing the final price, the client must press the pay button so the DeDe app registers the order on the database and returns the confirmation_
=== ...

=== <Runtime Scenario n>
