[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>

=== (Admin) Delete User

[plantuml,"(Admin) Delete User",png]
----
actor Admin
WebApp
RestAPI
DataBase

Admin -> WebApp: Request User List
WebApp -> RestAPI: Request User List
RestAPI -> DataBase: Request User List
DataBase -> RestAPI: Give User List
RestAPI -> WebApp: Represent User List
Admin -> WebApp: Select User To Remove
WebApp -> RestAPI: Request Delete User
RestAPI -> DataBase: Request Delete User
DataBase -> DataBase: Delete User POD Ubication
DataBase -> RestAPI: Give Updated User List
RestAPI -> WebApp: Represent Updated User List
----

=== (Admin) View Item Statistics

[plantuml,"(Admin) View Item Statistics",png]
----
actor Admin
WebApp
RestAPI
DataBase

Admin -> WebApp: Request Item List
WebApp -> RestAPI: Request Item List
RestAPI -> DataBase: Request Item List
DataBase -> RestAPI: Give Item List
RestAPI -> WebApp: Display Item List
Admin -> WebApp: Select Items
WebApp -> RestAPI: Request Selected Item Statistics
RestAPI -> DataBase: Request Selected Item Statistics
DataBase -> RestAPI: Give Selected Item Statistics
RestAPI -> WebApp: Display Item Statistics
Admin -> WebApp: Close Selected Item Statistics
WebApp -> RestAPI: Close Selected Item Statistics
RestAPI -> WebApp: Display Item List
----

=== (Admin) Monitor Order Status

[plantuml,"(Admin) Monitor Order Status",png]
----
actor Admin
WebApp
RestAPI
DataBase
UserPOD

Admin -> WebApp: Request Order List
WebApp -> RestAPI: Request Order List
RestAPI -> DataBase: Request Order List
DataBase -> RestAPI: Give Order List
RestAPI -> WebApp: Display Order List
Admin -> WebApp: Select Order To Display
WebApp -> RestAPI: Give Selected Order
RestAPI -> DataBase: Request Order Info.
DataBase -> RestAPI: Give Order Info.
RestAPI -> UserPOD: Request User Info.
UserPOD -> RestAPI: Give User Info.
RestAPI -> WebApp: Display Order Info.
Admin -> WebApp: Close Order Info.
WebApp -> RestAPI: Close Order Info.
RestAPI -> WebApp: Display Order List
----