== Runtime View

=== Register User

[plantuml,"RegisterUser",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database DataBase
User-> WebApp : Register
WebApp-> RestApi : send user data
RestApi -> DataBase : store user data
RestApi -> WebApp: Notify success
WebApp-> User: Log the user in the application
@enduml
----

This runtime view shows the process of registering a user, going through WebApp and ApiRest to database, storing the data in the database.

=== Login User DataBase
[plantuml,"LoginUserDataBase",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database DataBase
User-> WebApp : Login
WebApp-> RestApi : send login data
RestApi -> DataBase : find data
DataBase -> RestApi : send data
RestApi -> RestApi : check login data
RestApi -> WebApp: Notify success
WebApp-> User: Notify success
@enduml
----

This runtime view shows the login process of a user, going through WebApp and ApiRest to the DataBase, via the location stored in the database.

=== Login User POD
[plantuml,"LoginUserPOD",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database USER_POD
User-> WebApp : Enter WebID
WebApp-> RestApi : send WebID
RestApi -> USER_POD : get address from VCARD
USER_POD -> RestApi : send address
RestApi -> WebApp: send address
WebApp-> User: Show address
@enduml
----

This runtime view shows the login process of a user, going through WebApp and ApiRest to the user POD.

=== Visualize orders done

[plantuml,"VisualizeOrdersDone",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database DataBase
User -> WebApp: Ask for the done orders
WebApp -> RestApi: Send petition
RestApi -> DataBase: Ask for the client's orders by email
DataBase -> RestApi: Return the client's orders
RestApi -> WebApp: Return the orders
WebApp -> User: Show a list of client orders
@enduml
----
The user presses a button to visualize their previous orders, the WebApp send the petition to the RestApi. The RestApi asks for the client's orders from the user pod.
User pod returns the client's orders to the RestApi, and the RestApi sends them to the WebApp. The WebApp show a list of client orders.

=== Delete a product from the shopping chart

[plantuml,"DeleteProductFromTheShoppingCart",png]
----
@startuml
actor User
entity WebApp
User -> WebApp: Pulse the delete button
WebApp -> WebApp: Removes from the localstorage cart
@enduml
----
The user chooses the product and presses the button to delete it. The WebApp send this petition to the RestApi. The RestApi send the petition to delete a product to the POD, and the POD to the DataBase. Once the product is deleted from the DataBase, success is returned to the client.

=== Add products to the shopping cart

[plantuml,"AddProductsToTheShoppingCart",png]
----
@startuml
actor User
entity Webapp
entity Restapi
database Database
User-> Webapp: Selects a product cattegory
Webapp -> Restapi : Sends petition 
Restapi-> Database: Asks for the protucts of the selected cattegory
Database --> Restapi: Returns the searched products
Restapi --> Webapp : Returns the searched products
Webapp --> User: Shows the products
User-> Webapp: Presses de add button
Webapp -> Webapp: Storages the product in the localstorage cart
Webapp -> User: Shows the product in the cart so the user can pay anytime
@endtuml
----
_The user, identified as a client, selects the cattegory of the product of its choice and the DeDe app returns the filtered products to them. Then, the user can scroll through de app looking for the returned products and press the button "Add to Cart" to add them into the shopping cart and pay for them whenever they want._

=== Paying process
[plantuml,"PayingProcess",png]
----
@startuml
actor User
entity Webapp
entity Restapi
database Database
database UserPod
User-> Webapp: Presses the shipping page button
Webapp--> User: Takes the client to the paying page
User -> Webapp: Selects a distribution center for each product
User -> Webapp: Introduces its WebID
Webapp -> Restapi: Sends POD request
Restapi-> UserPod: Asks for the client's Address
UserPod --> Restapi: Returns the client Address
Restapi -> Restapi : Calculates the shipping price
Restapi --> Webapp : Returns the calculated data
Webapp --> User: Returns the shipping price and the final price
User-> Webapp: Presses the pay button
Webapp -> User: Returns the credit card form
User -> Webapp: Introduces its card data
Webapp -> Restapi: Sends a petition to save the order data
Restapi -> Database : Sends a petition to save the order data
Database -> Database : saves the order data
Restapi --> Webapp: Returns the order validation
Webapp --> User: Shows the order validation
@enduml
----
_The user presses the pay button on their shopping cart and the DeDe app takes them to the paying page where they can see the total price to pay in addition to the shipping price previously calculated by the DeDe application after asking the user's pod for their address and calculating the distance from that address to the distribution center. After seeing the final price, the client must press the pay button so the DeDe app registers the order on the database and returns the confirmation_

=== (Admin) Show users

[plantuml,"AdminShowUsers",png]
----
@startuml
actor Admin
entity WebApp
entity RestAPI
database DataBase

Admin -> WebApp: Request User List
WebApp -> RestAPI: Request User List
RestAPI -> DataBase: Request User List
DataBase -> RestAPI: Give User List
RestAPI -> WebApp: Represent User List
@enduml
----

=== (Admin) Add Item

[plantuml,"AdminAddItem",png]
----
@startuml
actor Admin
entity WebApp
entity RestAPI
database DataBase

Admin -> WebApp: Pulses the add product button
WebApp -> Admin: Shows form to add products
Admin-> WebApp : Fills the form
WebApp -> Restapi: Sends add petition
Restapi -> Database: Sends add petition
Database -> Database: Adds the product
WebApp -> WebApp: Displays the product
@enduml
----

=== (Admin) Monitor Order Status

[plantuml,"AdminMonitorOrderStatus",png]
----
@startuml
actor User
entity WebApp
entity RestAPI
database DataBase
database UserPOD

User-> WebApp: Request Order List
WebApp -> RestAPI: Request Order List
RestAPI -> DataBase: Request Order List (All, if user is an Admin, ot only the user ones if it is a Client)
DataBase -> RestAPI: Give Order List
RestAPI -> WebApp: Display Order List
WebApp -> User: Shows the order list
@enduml
----
