[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>

=== (Admin) Delete User

[plantuml,"(Admin) Delete User",png]
----
actor Admin
participant App
participant DataBase

Admin -> App: "Request Users List"
App -> DataBase: "Request Users List"
DataBase -> App: "Give User List"
App -> App: "Represent User List"
Admin -> App: "Select User To Remove"
App -> DataBase: "Request Delete User"
DataBase -> DataBase: "Delete User"
DataBase -> App: "Give Updated User List"
App -> App: "Represent Updated User List"
----

=== (Admin) View Item Statistics

[plantuml,"(Admin) View Item Statistics",png]
---
Admin -> App: "Request Item List"
App -> DataBase: "Request Item List"
DataBase -> App: "Give Item List"
App -> App: "Display Item List"
Admin -> App: "Select Items"
App -> DataBase: "Request Selected Item/s Statistics"
DataBase -> App: "Give Item/s Statistics"
App -> App: "Display Item Statistics"
Admin -> App: "Close Item Statistics"
App -> App: "Display Item List"
---

=== (Admin) Monitor Order Status

[plantuml,"(Admin) Monitor Order Status",png]
---
actor Admin
participant App
participant UserPOD
participant DataBase

Admin -> App: "Request Order List"
App -> DataBase: "Request Order List"
DataBase -> App: "Give Order List"
App -> App: "Display Order List"
Admin -> App: "Select Order To Display"
App -> UserPOD: "Request Order Info."
UserPOD -> App: "Give Order Info."
App -> App: "Display Order Info."
Admin -> App: "Close Order Info."
App -> App: "Display Order List"
---