[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Bob
database Pod as "Bob's Pod"
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
----
=== Visualize orders done

[plantuml,"Visualize orders done",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database USER_POD
User -> WebApp: Visualize the orders done
WebApp -> RestApi: Send user data
RestApi -> USER_POD: Ask for the client's orders
USER_POD -> RestApi: Return the client's orders
RestApi -> WebApp: Return the orders
WebApp -> User: Show a list of client orders
@enduml
----
The user presses a button to visualize their previous orders, the WebApp send the petition to the RestApi. The RestApi asks for the client's orders from the user pod.
User pod returns the client's orders to the RestApi, and the RestApi sends them to the WebApp. The WebApp show a list of client orders.

=== Delete a product from the shopping chart

[plantuml,"Delete a product from the shopping cart",png]
----
@startuml
actor User
entity WebApp
entity RestApi
database USER_POD
database DataBase
User -> WebApp: Delete a product
WebApp -> RestApi: Send user data
RestApi -> USER_POD: Delete product
USER_POD -> DataBase: Delete product
USER_POD -> RestApi: Return success
RestApi -> WebApp: Return success
WebApp -> User: Return success
@enduml
----
The user chooses the product and presses the button to delete it. The WebApp send this petition to the RestApi. The RestApi send the petition to delete a product to the POD, and the POD to the DataBase. Once the product is deleted from the DataBase, success is returned to the client.

=== <Runtime Scenario n>
