

=== 8.3. Internazionalization

The application will potentially deal with various locations and people, so make a multi-language application looks like the best decision. This decision must be done since the begining of the desing (lately will cost a lot of resources).

This allows us to reach a bigger audience and make the application more accesible.


=== 8.4. Security

Security is a key aspect of our software (and almost all) project. We will follow SOLID as recommendation to store our customers data and we will manage the data base to be always in a consistent state.


=== 8.5. Additional libraries

TODO


=== 8.6. Archiutecture and design patterns

TODO


=== 8.7 Code Quality standards

Code quality standars allows us to make an understable, maintainable and reusable code for future revisions and changes. Code should always have a correct structure to be easily understandable.

To achieve this we will use all tools programs give us and make correct decisions like design patters, use convention naming and try to reduce technical debt.

=== 8.8. Testability

Applications should be strongly tested. We will use user histories to make acceptance tests and unit test to test the rest of the application components and states during running process.

We think this is the best way to be sure the project works correctly.
